# GET CLIENTS
GET http://localhost:5000/simple-carservice-1.0-SNAPSHOT/api/clients

###

# GET CLIENT
GET http://localhost:5000/simple-carservice-1.0-SNAPSHOT/api/clients/c4804e0f-769e-4ab9-9ebe-0578fb4f00a6

###

# GET PORTRAIT
GET http://localhost:5000/simple-carservice-1.0-SNAPSHOT/api/clients/c4804e0f-769e-4ab9-9ebe-0578fb4f00a6/portrait

###

# PUT PORTRAIT
PUT http://localhost:5000/simple-carservice-1.0-SNAPSHOT/api/clients/c4804e0f-769e-4ab9-9ebe-0578fb4f00a6/portrait
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="portrait"; filename="sigrid.png'

< /home/student/Desktop/s184948/delete/CarService-jakartaee-servlet/images.jpeg
--boundary

###


PUT http://localhost:5000/simple-carservice-1.0-SNAPSHOT/api/clients/c4804e0f-769e-4ab9-9ebe-0578fb4f00a6/portrait
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="portrait"; filename="sigrid.png'

< D:\POBRANE\IMG-20230412-WA0000.jpg
--boundary--


###

# DELETE PORTRAIT
DELETE http://localhost:5000/simple-carservice-1.0-SNAPSHOT/api/clients/c4804e0f-769e-4ab9-9ebe-0578fb4f00a6/portrait


