# GET CLIENTS
GET http://localhost:5000/simple-carservice-1.0-SNAPSHOT/api/clients

###

# GET CLIENT
GET http://localhost:5000/simple-carservice-1.0-SNAPSHOT/api/clients/c4804e0f-769e-4ab9-9ebe-0578fb4f00a6

###

# DELETE CLIENT
DELETE http://localhost:5000/simple-carservice-1.0-SNAPSHOT/api/clients/c4804e0f-769e-4ab9-9ebe-0578fb4f00a6

###

# UPDATE CLIENT
PUT http://localhost:5000/simple-carservice-1.0-SNAPSHOT/api/clients
Content-Type: application/json

{
  "id": "c4804e0f-769e-4ab9-9ebe-0578fb4f00a6",
  "name": "NEW NAME",
  "surname": "KOWALSKI",
  "birthdate": "1990-10-10"
}

###

# GET PORTRAIT
GET http://localhost:5000/simple-carservice-1.0-SNAPSHOT/api/clients/c4804e0f-769e-4ab9-9ebe-0578fb4f00a6/portrait

###

# PUT PORTRAIT
PUT http://localhost:5000/simple-carservice-1.0-SNAPSHOT/api/clients/c4804e0f-769e-4ab9-9ebe-0578fb4f00a6/portrait
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="portrait";

< D:\POBRANE\ninja_turtles_PNG72.png>
--boundary

###

# DELETE PORTRAIT
DELETE http://localhost:5000/simple-carservice-1.0-SNAPSHOT/api/clients/c4804e0f-769e-4ab9-9ebe-0578fb4f00a6/portrait

###

## GARAGE ##


# GET GARAGES
GET http://localhost:5000/simple-carservice-1.0-SNAPSHOT/api/garages

###

# GET GARAGE
GET http://localhost:5000/simple-carservice-1.0-SNAPSHOT/api/garages/c4804e0f-769e-4ab9-9ebe-0578fb4f00a6

###

# DELETE GARAGE
DELETE http://localhost:5000/simple-carservice-1.0-SNAPSHOT/api/garages/c4804e0f-769e-4ab9-9ebe-0578fb4f00a6

###

# UPDATE GARAGE
PUT http://localhost:5000/simple-carservice-1.0-SNAPSHOT/api/garages
Content-Type: application/json

{
  "id": "c4804e0f-769e-4ab9-9ebe-0578fb4f00a6",
  "title": "NEW TITLE",
  "city": "NEW CITY",
  "zipCode": "90-900",
  "countEmployees": 5
}

###

## VISIT ##


# GET VISITS
GET http://localhost:5000/simple-carservice-1.0-SNAPSHOT/api/garages/c4804e0f-769e-4ab9-9ebe-0578fb4f00a6/visits

###

# GET GARAGE
GET http://localhost:5000/simple-carservice-1.0-SNAPSHOT/api/garages/c4804e0f-769e-4ab9-9ebe-0578fb4f00a6/visits/c4804e0f-769e-4ab9-9ebe-0578fb4f00a6

###

# DELETE GARAGE
DELETE http://localhost:5000/simple-carservice-1.0-SNAPSHOT/api/garages/c4804e0f-769e-4ab9-9ebe-0578fb4f00a6/visits/c4804e0f-769e-4ab9-9ebe-0578fb4f00a6

###

# UPDATE GARAGE
PUT http://localhost:5000/simple-carservice-1.0-SNAPSHOT/api/garages/c4804e0f-769e-4ab9-9ebe-0578fb4f00a6/visits
Content-Type: application/json

{
  "id": "c4804e0f-769e-4ab9-9ebe-0578fb4f00a6",
  "date": "2021-11-11",
  "VIN": "XXXXXXXXXXXXXXXXX"
}

###

# CREATE VISIT
POST http://localhost:5000/simple-carservice-1.0-SNAPSHOT/api/garages/c4804e0f-769e-4ab9-9ebe-0578fb4f00a6/visits
Content-Type: application/json

{
  "date": "2021-11-11",
  "VIN": "SDOTKDSOGFKDO"
}


